name: CI/CD Pipeline Biblioteka

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: uplifted-sol-493208-m7
  REGION: europe-central2
  BACKEND_IMAGE: europe-central2-docker.pkg.dev/uplifted-sol-493208-m7/projekt-biblioteka/spring-app
  FRONTEND_IMAGE: europe-central2-docker.pkg.dev/uplifted-sol-493208-m7/projekt-biblioteka/react-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Backend
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
        docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

    - name: Build and Push Frontend
      run: |
        cd KLIENT
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
        docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

    - name: Update YAMLs and Push to Git
      run: |
        sed -i "s|image: .*spring-app.*|image: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}|g" k8s/03-spring.yaml
        sed -i "s|image: .*react-app.*|image: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}|g" k8s/04-react.yaml
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git add k8s/03-spring.yaml k8s/04-react.yaml
        git commit -m "Update images to ${{ github.sha }} [skip ci]"
        git push
